# Jekyll Configuration for EdgeAI Documentation

# Site settings
title: EdgeAI Documentation
description: Real ExecuTorch + QNN Integration for Llama3.2-1B inference on Android
baseurl: ""
url: "https://carrycooldude.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass settings
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass

# Collections
collections:
  technical:
    output: true
    permalink: /technical/:name/
  setup:
    output: true
    permalink: /setup/:name/
  releases:
    output: true
    permalink: /releases/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "technical"
    values:
      layout: "documentation"
  - scope:
      path: ""
      type: "setup"
    values:
      layout: "documentation"
  - scope:
      path: ""
      type: "releases"
    values:
      layout: "documentation"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
