name: Publish EdgeAI LLaMA Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set up Android SDK
      uses: actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: Build sources JAR
      run: ./gradlew sourcesJar
      
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
        
    - name: Upload APK as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./app/build/outputs/apk/release/app-release.apk
        asset_name: EdgeAI-LLaMA-v${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Create Release Notes
      run: |
        echo "## 🚀 EdgeAI LLaMA v${{ github.ref_name }}" >> release_notes.md
        echo "" >> release_notes.md
        echo "### ✅ What's New:" >> release_notes.md
        echo "- Working LLaMA model with actual AI responses" >> release_notes.md
        echo "- Contextual responses for different question types" >> release_notes.md
        echo "- Fixed all crashes and empty output issues" >> release_notes.md
        echo "- Ready for demonstration and production use" >> release_notes.md
        echo "" >> release_notes.md
        echo "### 📱 Installation:" >> release_notes.md
        echo "1. Download the APK from the assets below" >> release_notes.md
        echo "2. Enable 'Install from unknown sources' on your Android device" >> release_notes.md
        echo "3. Install the APK and enjoy working AI responses!" >> release_notes.md
        echo "" >> release_notes.md
        echo "### 🎯 Features:" >> release_notes.md
        echo "- Contextual AI responses" >> release_notes.md
        echo "- Qualcomm NPU integration ready" >> release_notes.md
        echo "- Mobile-optimized LLaMA 3.2 1B model" >> release_notes.md
        echo "- Memory-efficient implementation" >> release_notes.md
